// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilribkgvbmuykzqrnrwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlscmlia2d2Ym11eWt6cXJucndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjkwMjYsImV4cCI6MjA2MTc0NTAyNn0.WAOzbRtfdyPunQhZXJDmx5PjZhYCPTZ8a02g9dxJt2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);